name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Test data simulation
        run: python src/data/simulate_sensors.py --out data/test.csv

      - name: Lint import
        run: python -c "import pandas, numpy, sklearn, torch, torchvision, streamlit"
